#!/bin/sh

for i in $(seq 2 9); do
  args=($(sed -e "s/;//g" sass/_colours.scss | cut -d" " -f$i))
  type=${args[0]}
  bright=${args[1]}
  dark=${args[2]}
  dim=${args[3]}
  dim=${dim/rgb/rgba}
  dim=${dim/)/,0.5)}
  
  convert -size 8x8 "canvas:$bright" -background none -shear 14x0 "theme/images/bullet_$type.png"
  convert -size 400x40 \( "canvas:$dark" -background none -shear 14x0 \) \( "canvas:$bright" -background none -shear 14x0 \) -append "theme/images/nav_$type.png"
  convert -size 1000x40 "canvas:$bright" -background none -shear 14x0 "theme/images/bleed_${type}.png"
  convert -size 20x800 "canvas:$dim" "theme/images/img_$type.png"
  convert arrow_black.png -fill "$bright" -opaque black theme/images/arrow_${type}.png
  convert theme/images/arrow_${type}.png -flop theme/images/arrow_${type}_back.png
  convert theme/images/arrow_${type}.png -rotate 90 theme/images/arrow_${type}_down.png
done

convert arrow_black.png -fill "rgb(255,255,255)" -opaque black theme/images/arrow_hover.png
convert theme/images/arrow_hover.png -flop theme/images/arrow_hover_back.png
convert theme/images/arrow_hover.png -rotate 90 theme/images/arrow_hover_down.png

capheight=100
offset=14
width=24
crop="-crop ${width}x${capheight}+${offset}x0"
convert -size 14x$capheight canvas:none -size 200x$capheight canvas:white +append -background none -shear 14x0 $crop "theme/images/cap_right.png"
convert -size 14x$capheight canvas:white -size 200x$capheight canvas:none +append -background white -shear 14x0 $crop "theme/images/cap_left.png"

update_styles
