#!/bin/sh

feature="88,14,173"
featuredim="156,106,214"
featuredark="55,4,112"
snippet="5,125,159"
snippetdim="97,183,207"
snippetdark="2,81,103"
podcast="177,241,0"
podcastdim="212,248,112"
podcastdark="115,157,0"
about="255,187,0"
aboutdim="255,218,115"
aboutdark="166,122,0"

for type in feature snippet podcast about; do
  eval bright="\$${type}"
  eval dim="\$${type}dim"
  eval dark="\$${type}dark"

  convert -size 8x8 "canvas:rgb($bright)" -background none -shear 14x0 "theme/images/bullet_$type.png"
  convert -size 400x40 \( "canvas:rgb($dark)" -background none -shear 14x0 \) \( "canvas:rgb($bright)" -background none -shear 14x0 \) -append "theme/images/nav_$type.png"
  convert -size 1000x40 "canvas:rgb($bright)" -background none -shear 14x0 "theme/images/bleed_${type}.png"
  convert -size 20x400 "canvas:rgba($dim,0.5)" "theme/images/img_$type.png"
  convert arrow_black.png -fill "rgb($bright)" -opaque black theme/images/arrow_${type}.png
  convert theme/images/arrow_${type}.png -flop theme/images/arrow_${type}_back.png
done

convert arrow_black.png -fill "rgb(255,255,255)" -opaque black theme/images/arrow_hover.png
convert theme/images/arrow_hover.png -flop theme/images/arrow_hover_back.png

capheight=100
offset=14
width=24
crop="-crop ${width}x${capheight}+${offset}x0"
convert -size 14x$capheight canvas:none -size 200x$capheight canvas:white +append -background none -shear 14x0 $crop "theme/images/cap_right.png"
convert -size 14x$capheight canvas:white -size 200x$capheight canvas:none +append -background white -shear 14x0 $crop "theme/images/cap_left.png"

sass --style compact --update sass/:theme/styles/